<template>

    <section class="">
        <!-- Footer -->
        <footer class="bg-secondary text-white text-center text-md-start" id="footer">
            <!-- Grid container -->
            <div class="container p-4">
            <!--Grid row-->
            <div class="row">

                <!--Grid column-->
                <div class="col-lg-6 col-md-6 mb-4 mb-md-0">
                    <h2>Site Map</h2>

                    <ul class="list-unstyled mb-0">
                        <li>
                        <a href="#!" class="text-white">Manage Organization1</a>
                        </li>
                        <li>
                        <a href="#!" class="text-white">Refister Applicant</a>
                        </li>
                        <li>
                        <a href="#!" class="text-white">Organiza Aid Appeal</a>
                        </li>
                        <li>
                        <a href="#!" class="text-white">Record Contribution</a>
                        </li>
                        <li>
                        <a href="#!" class="text-white">View Appeals</a>
                        </li>
                        <li>
                        <a href="#!" class="text-white">Record Aid Disbursement</a>
                        </li>
                        <li>
                        <a href="#!" class="text-white">About Us</a>
                        </li>
                        <li>
                        <a href="#!" class="text-white">FAQ</a>
                        </li>
                    </ul>
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-6 col-md-12 mb-4 mb-md-0">

                <img src="../../../public/images/samplelogo.png" alt="logo" class="align-middle">

                <h5 class="mt-3">Contact Information</h5>

                <table class="table text-white">
                <tbody>
                    <tr>
                    <td>Email</td>
                    <td>AssistLink@mail.com</td>
                    </tr>
                    <tr>
                    <td>Phone</td>
                    <td>000-000-000</td>
                    </tr>
                </tbody>
                </table>
                </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->
            </div>
            <!-- Grid container -->

            <!-- Copyright -->
            <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            <a class="text-white" href="#">© 2022 Copyright: AssistLink.com</a>
            </div>
            <!-- Copyright -->
        </footer>
        <!-- Footer -->
    </section>
</template>

<script>
    export default {
        mounted() {
            console.log('Component mounted.')
        }
    }
</script>